### ISSUE TITLE
"it does not work" ...

### ISSUE THREAD

**Issue by lemmy04** [MrYadro/TDeskDroid#8]
Yes i know, does not tell you much, but here's what I got:

mathias@kirika:~/TDeskDroid-master> python3 main.py 
Downloading [desktop => android] mapping
Traceback (most recent call last):
  File "main.py", line 272, in <module>
    TDeskDroid().convert()
  File "main.py", line 256, in convert
    self._updateThemesMap()
  File "main.py", line 48, in _updateThemesMap
    self._themeMapCommit = self._getCommitId(THEME_MAP_COMMIT_URL)
  File "main.py", line 44, in _getCommitId
    return requests.get(url).json()['sha']
KeyError: 'sha'

any ideas?

**Comment by MrYadro** [comment]
How about now?

**Comment by lemmy04** [comment]
ok it does *something*, but the resulting theme is empty... I'm trying to convert the attached theme, the resulting attheme file only contains this:

mathias@kirika:~/TDeskDroid/android> cat Luna.attheme 
// ////////////////////////////////////////
// 
// This Telegram android-theme was converted from desktop-theme using TDeskDroid utility.
// 
// Convertion parameters:
//      TDeskDroid : '1.0.0'
//   Desktop theme : 'Luna.tdesktop-theme'
//       theme.map : 'None'
// theme_alpha.map : 'None'
//     default.map : 'None'
// 
// If you have any bugs feel free to contact:
// https://t.me/TThemesHQ
// https://github.com/MrYadro/TDeskDroid/issues/new
// 
// ////////////////////////////////////////

findme=#ff00ffff
whatever=#ffff00ff

[Luna.tdesktop-theme.zip](https://github.com/MrYadro/TDeskDroid/files/893850/Luna.tdesktop-theme.zip)

**Comment by MrYadro** [comment]
Do you have internet connection on that PC, because for some reason it can't download map files.

**Comment by lemmy04** [comment]
I do, but the map files it downloads only contain the single line "404: Not Found"

**Comment by MrYadro** [comment]
Do you have access to https://raw.githubusercontent.com/TThemes/TThemeMap/master/desktop_android.map ?

**Comment by lemmy04** [comment]
yup, should I just grab that and stick it into the maps folder?

**Comment by MrYadro** [comment]
python should grab it for you (: But for some reason you get 404 on every request, weird.

**Comment by lemmy04** [comment]
i can download them just fine with curl... no idea what&where python tries to grab them.

**Comment by lemmy04** [comment]
ok I downloaded the map files manually, put them into the maps folder, and commented out the pieces in main.py that save the (failed) downloads, now I got an android theme from the desktop theme :)
Still would be interesting why the script tris to download something from somewhere else than the urls in the source.

Also, the attheme does NOT contain the image, and I get a warning:

 Converting 'Luna'
Warning: failed to convert background

**Comment by gipnokote** [comment]
@lemmy04 Had the same problem (about the background), checked the code and saw that it always expects the background filename to be "background.png" or "background.jpg". In my theme it was different, so just renamed it to what it expects, and problem was gone.
